# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FeatureExport.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FeatureExport.proto',
  package='featureExport',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x46\x65\x61tureExport.proto\x12\rfeatureExport\"\x8f\x03\n\x07OneSide\x12\x18\n\x10preShoulderFront\x18\x01 \x01(\x02\x12\x15\n\rpreShoulderUp\x18\x02 \x01(\x02\x12\"\n\x1aupperArmPointingDirectionX\x18\x03 \x01(\x02\x12\"\n\x1aupperArmPointingDirectionY\x18\x04 \x01(\x02\x12\"\n\x1aupperArmPointingDirectionZ\x18\x05 \x01(\x02\x12!\n\x19\x66orearmPointingDirectionX\x18\x06 \x01(\x02\x12!\n\x19\x66orearmPointingDirectionY\x18\x07 \x01(\x02\x12!\n\x19\x66orearmPointingDirectionZ\x18\x08 \x01(\x02\x12 \n\x18shoulderInternalRotation\x18\t \x01(\x02\x12\x18\n\x10\x66orearmPronation\x18\n \x01(\x02\x12\x12\n\nelbowAngle\x18\x0b \x01(\x02\x12\x0e\n\x06wristX\x18\x0c \x01(\x02\x12\x0e\n\x06wristY\x18\r \x01(\x02\x12\x0e\n\x06wristZ\x18\x0e \x01(\x02\"\x90\x02\n\x10\x45xportFrameProto\x12\r\n\x05kTime\x18\x01 \x01(\x01\x12\x13\n\x0bvisualIndex\x18\x02 \x01(\x05\x12\x18\n\x10trunkFrontalTilt\x18\x03 \x01(\x02\x12\x18\n\x10trunkLateralTilt\x18\x04 \x01(\x02\x12)\n\trightSide\x18\x05 \x01(\x0b\x32\x16.featureExport.OneSide\x12(\n\x08leftSide\x18\x06 \x01(\x0b\x32\x16.featureExport.OneSide\x12\x19\n\x11trunkOrientationX\x18\x07 \x01(\x02\x12\x19\n\x11trunkOrientationY\x18\x08 \x01(\x02\x12\x19\n\x11trunkOrientationZ\x18\t \x01(\x02\"n\n\x12\x45xportSessionProto\x12/\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x1f.featureExport.ExportFrameProto\x12\x13\n\x0bsubjectName\x18\x02 \x01(\t\x12\x12\n\nrecordName\x18\x03 \x01(\tB \xaa\x02\x1dGoogle.Protobuf.FeatureExportb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ONESIDE = _descriptor.Descriptor(
  name='OneSide',
  full_name='featureExport.OneSide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preShoulderFront', full_name='featureExport.OneSide.preShoulderFront', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='preShoulderUp', full_name='featureExport.OneSide.preShoulderUp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upperArmPointingDirectionX', full_name='featureExport.OneSide.upperArmPointingDirectionX', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upperArmPointingDirectionY', full_name='featureExport.OneSide.upperArmPointingDirectionY', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upperArmPointingDirectionZ', full_name='featureExport.OneSide.upperArmPointingDirectionZ', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forearmPointingDirectionX', full_name='featureExport.OneSide.forearmPointingDirectionX', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forearmPointingDirectionY', full_name='featureExport.OneSide.forearmPointingDirectionY', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forearmPointingDirectionZ', full_name='featureExport.OneSide.forearmPointingDirectionZ', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shoulderInternalRotation', full_name='featureExport.OneSide.shoulderInternalRotation', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forearmPronation', full_name='featureExport.OneSide.forearmPronation', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='elbowAngle', full_name='featureExport.OneSide.elbowAngle', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wristX', full_name='featureExport.OneSide.wristX', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wristY', full_name='featureExport.OneSide.wristY', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wristZ', full_name='featureExport.OneSide.wristZ', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=438,
)


_EXPORTFRAMEPROTO = _descriptor.Descriptor(
  name='ExportFrameProto',
  full_name='featureExport.ExportFrameProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kTime', full_name='featureExport.ExportFrameProto.kTime', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visualIndex', full_name='featureExport.ExportFrameProto.visualIndex', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trunkFrontalTilt', full_name='featureExport.ExportFrameProto.trunkFrontalTilt', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trunkLateralTilt', full_name='featureExport.ExportFrameProto.trunkLateralTilt', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rightSide', full_name='featureExport.ExportFrameProto.rightSide', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leftSide', full_name='featureExport.ExportFrameProto.leftSide', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trunkOrientationX', full_name='featureExport.ExportFrameProto.trunkOrientationX', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trunkOrientationY', full_name='featureExport.ExportFrameProto.trunkOrientationY', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trunkOrientationZ', full_name='featureExport.ExportFrameProto.trunkOrientationZ', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=713,
)


_EXPORTSESSIONPROTO = _descriptor.Descriptor(
  name='ExportSessionProto',
  full_name='featureExport.ExportSessionProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frames', full_name='featureExport.ExportSessionProto.frames', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subjectName', full_name='featureExport.ExportSessionProto.subjectName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recordName', full_name='featureExport.ExportSessionProto.recordName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=715,
  serialized_end=825,
)

_EXPORTFRAMEPROTO.fields_by_name['rightSide'].message_type = _ONESIDE
_EXPORTFRAMEPROTO.fields_by_name['leftSide'].message_type = _ONESIDE
_EXPORTSESSIONPROTO.fields_by_name['frames'].message_type = _EXPORTFRAMEPROTO
DESCRIPTOR.message_types_by_name['OneSide'] = _ONESIDE
DESCRIPTOR.message_types_by_name['ExportFrameProto'] = _EXPORTFRAMEPROTO
DESCRIPTOR.message_types_by_name['ExportSessionProto'] = _EXPORTSESSIONPROTO

OneSide = _reflection.GeneratedProtocolMessageType('OneSide', (_message.Message,), dict(
  DESCRIPTOR = _ONESIDE,
  __module__ = 'FeatureExport_pb2'
  # @@protoc_insertion_point(class_scope:featureExport.OneSide)
  ))
_sym_db.RegisterMessage(OneSide)

ExportFrameProto = _reflection.GeneratedProtocolMessageType('ExportFrameProto', (_message.Message,), dict(
  DESCRIPTOR = _EXPORTFRAMEPROTO,
  __module__ = 'FeatureExport_pb2'
  # @@protoc_insertion_point(class_scope:featureExport.ExportFrameProto)
  ))
_sym_db.RegisterMessage(ExportFrameProto)

ExportSessionProto = _reflection.GeneratedProtocolMessageType('ExportSessionProto', (_message.Message,), dict(
  DESCRIPTOR = _EXPORTSESSIONPROTO,
  __module__ = 'FeatureExport_pb2'
  # @@protoc_insertion_point(class_scope:featureExport.ExportSessionProto)
  ))
_sym_db.RegisterMessage(ExportSessionProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\035Google.Protobuf.FeatureExport'))
# @@protoc_insertion_point(module_scope)
